### ISSUE TITLE
Relax BidirectionalIterator requirements?

### ISSUE THREAD

**Issue by vinniefalco** [cplusplus/networking-ts#42]
To put it simply, the C++ specification is deficient when it comes to defining iterator concepts, because it conflates the traversal and value access concerns. This is fully described here:
http://www.boost.org/doc/libs/1_62_0/libs/iterator/doc/new-iter-concepts.html

I propose that the networking proposal break new ground and push for addressing this defect. Specifically, for the **ConstBufferSequence** and **MutableBufferSequence** type requirements, replace the **BidirectionalIterator** requirement on `const_iterator` with the dual requirements **ReadableIterator** and **BidirectionalTraversalIterator**, defined here:
http://www.boost.org/doc/libs/1_62_0/libs/iterator/doc/new-iter-concepts.html#readable-iterators-lib-readable-iterators

Rationale: This allows more flexible operations on buffer sequences, such as applying range transformations to the value type. Without this change, implementations that transform buffer sequences (such as concatenating them, adjusting the byte range they represent, or converting from mutable to const sequences) become overly complex, inefficient, or impossible.

Here are examples of buffer sequence transformations in use today which would be disallowed by the current **BidirectionalIterator** requirements in the networking TS:

https://github.com/vinniefalco/Beast/blob/70b8555cdca69b9c5777db02115d30d1c1aad631/include/beast/core/buffer_cat.hpp#L22

https://github.com/vinniefalco/Beast/blob/70b8555cdca69b9c5777db02115d30d1c1aad631/include/beast/core/buffers_adapter.hpp#L17

https://github.com/vinniefalco/Beast/blob/70b8555cdca69b9c5777db02115d30d1c1aad631/include/beast/core/consuming_buffers.hpp#L20

https://github.com/vinniefalco/Beast/blob/70b8555cdca69b9c5777db02115d30d1c1aad631/include/beast/core/prepare_buffers.hpp#L135

One implementation above, `buffer_cat`, is particularly useful as it allows multiple system calls (to read or write on a socket) to be reduced to one. Consider a network protocol that sends objects which have multiple parts, such as a message header followed by a message body. The header and body could each be represented by a **ConstBufferSequence**. `buffer_cat` allows sending the entire message in a single system call instead of doing it in two separate calls. This has been used in the wild to achieve impressive decreases in latency for a HTTP server. The current implementation of `buffer_cat` is rather elegant, it uses the equivalent of a `std::variant` to efficiently transform the inputs without making a copy of the sequences:
https://github.com/vinniefalco/Beast/blob/70b8555cdca69b9c5777db02115d30d1c1aad631/include/beast/core/detail/buffer_cat.hpp#L22

This implementation is unfortunately non conforming because the iterators it defines, do not meet the requirements of **BidirectionalIterator** since they return an rvalue:
https://github.com/vinniefalco/Beast/blob/70b8555cdca69b9c5777db02115d30d1c1aad631/include/beast/core/detail/buffer_cat.hpp#L103
This was done because `buffer_cat` allows conversion from mutable sequences to const sequences. For example, if `a` and `b` are **ConstBufferSequence\* objects, and `c` is a **MutableBufferSequence**, the expression `buffer_cat(a, b, c)` returns an object representing the concatenation of `a`, `b`, and `c`, whose type meets the requirements of **ConstBufferSequence**.

The alternative to the elegant, current implementation of `buffer_cat` is one that uses a `std::vector` equivalent to store a precomputed version of the concatenated sequence. Its true that a specialization could make this vector implementation required in only a subset of use cases but the solution is non-ideal.

For this reason, I urge the authors to consider requiring only **ReadableIterator** and **BidirectionalTraversalIterator** for iterators representing buffer sequences.

**Comment by jwakely** [comment]
This belongs in a proposal to the committee, not as a github issue.

Speaking not as the TS editor, IMHO this TS isn't the place to make such a change. The Ranges TS is a better vehicle for doing it, so that we don't have inconsistent approaches in different TSs.

**Comment by vinniefalco** [comment]
Perhaps you are right, but my immediate concern is that the `BidirectionalIterator` requirement will break Beast.

**Comment by vinniefalco** [comment]
I brought it up here
https://github.com/ericniebler/range-v3/issues/479

**Comment by ericniebler** [comment]
The Ranges TS already loosens the iterator requirements to permit random access iterators to return rvalues. The proxy iterators paper extends this to permit iterators that return proxies, like vector<bool>. Without looking at your specific use cases, I'll hazard to say this should be sufficient for your needs.

**Comment by vinniefalco** [comment]
@ericniebler Thanks for getting back to me. I admit to still being a novice at understanding how the committee process works (although Howard Hinnant has been helping me come up to speed). With respect to Beast and the iterators it provides, is the best course of action for me to simply meet the requirements of **ReadableIterator** and **BidirectionalTraversalIterator**, and keep my fingers crossed that eventually this problem will sort itself out in the standard?

**Comment by ericniebler** [comment]
IMO your best bet is to read the concept definitions in the Ranges TS and the Proxy Iterators paper. There's no reason to hope for the best when you can easily answer the question for yourself. Also, there is my range-v3 library that implements all of this, and @CaseyCarter's cmcstl2 library that does likewise using Concepts proper.

**Comment by vinniefalco** [comment]
Someone has helpfully pointed out that N4606 [path.itr]/2 has a carve-out for **BidirectionalIterator** that completely covers my use-case, maybe the Networking TS can adopt it? I'm thinking about a change to the proposed wording. Specifically:

Table 12 row 1:
**return type** _An iterator type whose value type is convertible to `mutable_buffer`, and which satisfies all the requirements for bidirectional iterators (C++Std [bidirectional.iterators]) except that, for two dereferenceable iterators `a` and `b` where `a == b`, there is no requirement that `_a`and`_b` are bound to the same object._

Table 13 row 1:
**return type** _An iterator type whose value type is convertible to `const_buffer`, and which satisfies all the requirements for bidirectional iterators (C++Std [bidirectional.iterators]) except that, for two dereferenceable iterators `a` and `b` where `a == b`, there is no requirement that `_a`and`_b` are bound to the same object._

**Comment by vinniefalco** [comment]
Part of #43 now, further discussion can happen there

**Comment by vinniefalco** [comment]
The issue of iterator requirements in the Networking TS is now in the Active Issues List:
http://cplusplus.github.io/LWG/lwg-active.html#2779
