### ISSUE TITLE
I'll ask the obvious, dumb question:

### ISSUE THREAD

**Issue by vinniefalco** [cplusplus/networking-ts#45]
> I can't find any mention of SSL or TLS in the draft?

Why aren't SSL or TLS mentioned in the draft?

**Comment by zygoloid** [comment]
... that's not a question. :)

**Comment by vinniefalco** [comment]
@zygoloid Now it is!

**Comment by jwakely** [comment]
See http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4370.html#network.scope

> Features that are considered outside the scope of this proposal include:
> - Protocol implementations such as HTTP, SMTP or FTP.
> - Encryption (e.g. SSL, TLS).

We have to start somewhere, and it's not with TLS. That can be built on top of the foundations, later.

**Comment by vinniefalco** [comment]
Makes sense, we've waited long enough for having a socket in the standard.

**Comment by jwakely** [comment]
Yeah exactly :-)

**Comment by mclow** [comment]
That being said, it's an obvious (and IMHO, necessary) V2 feature.

**Comment by vinniefalco** [comment]
Is there a place where there is some sort of discussion and planning for a standardized SSL? The security considerations make it unlike any other implementation in the standard. I strongly doubt we will get a good result if we require **N** implementations from **N** vendors.
