### ISSUE TITLE
Where is the null_buffers?

### ISSUE THREAD

**Issue by vinniefalco** [cplusplus/networking-ts#49]
I don't see `null_buffers` in the TS:
http://www.boost.org/doc/libs/1_62_0/doc/html/boost_asio/overview/core/reactor.html

Is it there?

**Comment by jwakely** [comment]
No, it wasn't proposed for inclusion.

**Comment by ghost** [comment]
So basically you are going to ignore the BSD 1983 standard of reactor design (epoll, select, kqueue, poll) and just force the Windows IOCP model onto everyone? Proactor pattern is not native of any Unix system and that is why ASIO has null buffers to allow one to use the reactor design instead.

By ignoring the Unix native pattern and forcing the Windows pattern into standard is completely unacceptable.

**Comment by alexhultman** [comment]
You are going to standardize this into C++ over my dead body I can tell you this.

**Comment by chriskohlhoff** [comment]
It is now spelled `basic_socket::wait()` and `basic_socket::async_wait()`. (And likewise for `basic_socket_acceptor`.)

**Comment by jwakely** [comment]
I don't think we need `null_buffers` when there is a more natural way to wait for readiness, using a dedicated method. We also don't need to worry about silly overreactions, so I'm closing this.
