### ISSUE TITLE
Normative references section doesn't actually include any normative references

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/networking-ts#66]
There should be a list, and the abbreviations (p2) probably should be in normative text rather than a note.

**Comment by jwakely** [comment]
This is being addressed in response to an NB comment on the PDTS ballot. See https://github.com/cplusplus/networking-ts/commit/bd8ff6c2ed45e9407f9cd6afc5ca564b45183a4c on branch https://github.com/cplusplus/networking-ts/tree/pdts-ballot-resolutions
