### ISSUE TITLE
[async.reqmts.service] uses is_base_of_v

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/networking-ts#67]
The base standard is C++14, so 'is_base_of_v` doesn't exist.

**Comment by jwakely** [comment]
It gets it from the Library Fundamentals TS, see [namespaces]. That's added to the references by https://github.com/cplusplus/networking-ts/commit/38ece1e1f4fca4be34e57dce825ae5771ea3516d on branch https://github.com/cplusplus/networking-ts/tree/pdts-ballot-resolutions

**Comment by timsong-cpp** [comment]
Ah yes, I was spot-checking my HTML version and didn't read enough to notice the pervasive use of `string_view`. Sorry for the noise!
